### PR TITLE
Redisign

### LINKED ISSUE #42: Implement dark mode
Provide ability to change color theme.

### LINKED ISSUE #53: Application Redesign
- Add a placeholder to the Search Movies input.
- Change color and font used in the logo. (Make sure the logo looks good in both dark and light themes). Come up with a color palette based on the logo (Dark Theme First).
- Find and add a custom font that looks nice in darkmode, lightmode and near the movie details.
- Add shadows to Movie Cards and Actor Cards when hovering. Add a transition for the shadows so they don't "pop-in".
- Investigate adding a shadow to the Header component.
- Redesign the Actor page:
    - Remove "Also Known As" if there is no data there.
    - Remove lots of empty space by centering the actor information.
    - Make sure the movies list takes up the empty space.
image

TODO: ADD MORE IDEAS HERE

### PR DESCRIPTION
**Pull request by Aleshchenko-V**
Redesign completed;
Implemented theme switcher;
Rewrite some components.
Closes #42
Closes #53

### CODE REVIEW

**Comment by TheSecondCore** [comment]
I am able to get to Discovery Mode through the Movie Details page. That shouldn't be possible:

image

**Comment by TheSecondCore** [comment]
The Sidebar and the Toggle-Theme buttons don't look like buttons.

I propose we put them in the header:
 - Discovery mode can be a button that opens the sidebar automatically.
 - Dark/Light theme toggle can go near the TMDB/GitHub logos - although make sure to make it look different enough so it looks like a button or a switch. We can use something like this that looks cool: https://codepen.io/theprogrammingexpert/pen/vYKYKrz

**Comment by TheSecondCore** [comment]
Align the movie info to the info categories so they aren't mismatched:

image

Align the Actor List so they are positioned under the movie details and the movie cover:

image

**Comment by TheSecondCore** [comment]
Dark Theme text has a bad contrast ratio against the background. Make sure the contrast is at least 4.5 according to https://webaim.org/resources/contrastchecker/

image

**Review by Zeebro2223 — APPROVED** [review]

**Pull request merged**
